### ISSUE TITLE
Running tests creates undesired xdmf-files

### ISSUE THREAD

**Issue by KulaginVladimir** [festim-dev/FESTIM#693] opened 2024-01-31 14:47 UTC
Currently, I observe that running tests with pytest results in export of XDMF for temperature. After the analysis, I found that it is caused by `test_convective_flux` due to unspecified tmp-folder for `XDMFExport`:
https://github.com/festim-dev/FESTIM/blob/e1554d356337a9e3b43bb1a1d884205a26eedfcb/test/system/test_misc.py#L7-L29

Possibly, it worth a fix just providing a `tmpdir` argument to the test and `F.XDMFExport.folder`

**Comment by RemDelaporteMathurin** [comment] 2024-01-31 14:54
This may be a duplicate of #530

**Comment by KulaginVladimir** [comment] 2024-01-31 15:01
@RemDelaporteMathurin Phenomenologically, yes. Shall I close this issue then?

**Closed** 2024-01-31 15:08 UTC
